#! /bin/sh
# Docs https://wiki.archlinux.org/index.php/Bspwm
eval `ssh-agent -s`
ssh-add "${HOME}/.ssh/id_rsa"

sxhkd &

bspc monitor eDP-1 -d term web music IV V 
bspc monitor DP-1 -d term web VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true
#bspc config external_rules_command "$(which external_rules)"

xrandr --output eDP-1 --auto --output DP-1 --auto --right-of eDP-1
MONITOR=DP-1 polybar -c ~/.config/polybar/ethernet top &
MONITOR=eDP-1 polybar -c ~/.config/polybar/ethernet top &
feh --bg-fill ~/.config/dotfile/background.jpg

