#! /bin/sh
# Docs https://wiki.archlinux.org/index.php/Bspwm

xbindkeys &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
eval `ssh-agent -s`
ssh-add "${HOME}/.ssh/id_rsa"

sxhkd &

PRIMARY=$(xrandr --query | grep '\bconnected\b' | grep primary | awk '{print $1}')
SECONDARY=$(xrandr --query | grep '\bconnected\b' | grep -v primary | awk '{print $1}')

bspc monitor ${PRIMARY} -d term web music IV V 
bspc monitor ${SECONDARY} -d term web VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true
#bspc config external_rules_command "$(which external_rules)"
bspc rule -a Gimp follow=on state=floating

xrandr --output ${PRIMARY} --auto --output ${SECONDARY} --auto --right-of ${PRIMARY}
MONITOR=${PRIMARY} polybar -c ~/.config/polybar/ethernet top &
MONITOR=${SECONDARY} polybar -c ~/.config/polybar/ethernet top &
feh --bg-fill ~/.config/dotfile/background.jpg

